- package_name: certifi
  version: 2018.10.15
- package_name: chardet
  version: 3.0.4
- package_name: coreapi
  version: 2.3.3
- package_name: coreschema
  version: 0.0.4
- package_name: Django
  version: 1.11.16
- package_name: django-rest-framework
  version: 0.1.0
- package_name: djangorestframework
  version: 3.9.0
- package_name: idna
  version: "2.7"
- package_name: itypes
  version: 1.1.0
- package_name: Jinja2
  version: "2.10"
- package_name: MarkupSafe
  version: 1.1.0
- package_name: Pygments
  version: 2.2.0
- package_name: pytz
  version: "2018.7"
- package_name: requests
  version: 2.20.0
- package_name: uritemplate
  version: 3.0.0
- package_name: urllib3
  version: 1.24.1
