version: '3'
services:
  workstation:
    container_name: workstation
    build:
      context: .
      dockerfile: workstation/Dockerfile
    stdin_open: true
    tty: true
    links:
      - target
    volumes:
      - ./pip-requirements-test:/workstation-home/pip-requirements-test

  target:
    build:
      context: .
      dockerfile: target/Dockerfile
    stdin_open: true
    tty: true
    container_name: target
